version: '3'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=postgresdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
