version: '3'

networks:
  api:
    driver: bridge

services:
  api:
    container_name: api
    depends_on:
      - postgresdb
      - mongodb
      - redisdb
    build: .
    volumes:
      - .:/home/node/api
    command: yarn dev
    networks:
      - api
    ports:
      - 3333:3333


  postgresdb:
    image: postgres
    container_name: postgres
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=postdb
    networks:
      - api
    ports:
      - "5432:5432"
  

  mongodb:
    image: mongo
    container_name: mongo
    networks:
      - api
    ports:
      - "27017:27017"
  

  redisdb:
    image: redis
    container_name: redis
    networks:
      - api
    ports:
      - "6379:6379"