version: '3'

services:
  postgresdb:
    image: postgres
    container_name: gobarber_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gobarber
      - POSTGRES_DB=gobarber
    ports:
      - "5432:5432"
